apiVersion: v1
kind: Service
metadata:
  name: web-app-1-service
  namespace: dev
spec:
  selector:
    app: web-app-1
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
      NodePort: 30000
  type: NodePort
